/**
 * Demo Seed — Shared Engine Helpers
 *
 * Thin wrappers around the real assessment/mastery engines
 * (src/lib/assessment, src/lib/mastery) so the demo data is generated by
 * actually exercising server-side grading and mastery status transitions,
 * not by hand-writing AssessmentAttempt/AttemptResponse/StudentProgress rows.
 */

import { prisma } from '@/lib/db'
import { startAttempt, gradeAndSubmit } from '@/lib/assessment'
import type { SubmitInput } from '@/lib/assessment'
import { updateProgressAfterAttempt } from '@/lib/mastery'
import type { AssessmentType, StudentProgressStatus } from '@prisma/client'

export async function findAssessment(
  benchmarkId: string,
  assessmentType: AssessmentType
): Promise<{ id: string } | null> {
  return prisma.assessment.findFirst({
    where: { benchmarkId, assessmentType },
    select: { id: true },
  })
}

interface QuestionFixture {
  questionId: string
  correctOptionId: string
  wrongOptionId: string
}

async function loadAssessmentQuestions(assessmentId: string): Promise<QuestionFixture[]> {
  const rows = await prisma.assessmentQuestion.findMany({
    where: { assessmentId },
    orderBy: { sequenceOrder: 'asc' },
    select: {
      question: {
        select: {
          id: true,
          options: { select: { id: true, isCorrect: true } },
        },
      },
    },
  })

  return rows.map((r) => ({
    questionId: r.question.id,
    correctOptionId: r.question.options.find((o) => o.isCorrect)!.id,
    wrongOptionId: r.question.options.find((o) => !o.isCorrect)!.id,
  }))
}

export interface DriveAttemptResult {
  attemptId: string
  score: number
  passed: boolean
}

/**
 * Drive one real attempt through the actual grading + mastery engines
 * (startAttempt → gradeAndSubmit → updateProgressAfterAttempt).
 *
 * The first `correctCount` questions (by sequence order) are answered
 * correctly, the rest wrong. Pass a large number (e.g. 999) for "all correct"
 * or 0 for "all wrong" — the count is clamped to the assessment's question count.
 */
export async function driveAttempt(
  assessmentId: string,
  studentId: string,
  correctCount: number,
  confidence?: 0 | 1 | 2
): Promise<DriveAttemptResult> {
  const questions = await loadAssessmentQuestions(assessmentId)
  const { attemptId } = await startAttempt(assessmentId, studentId)

  const responses: SubmitInput['responses'] = questions.map((q, i) => ({
    questionId: q.questionId,
    selectedOptionId: i < correctCount ? q.correctOptionId : q.wrongOptionId,
    ...(confidence !== undefined ? { confidence } : {}),
    timeSeconds: 15,
  }))

  const result = await gradeAndSubmit({ attemptId, responses }, studentId)
  await updateProgressAfterAttempt(attemptId, studentId)

  return { attemptId, score: result.score, passed: result.passed }
}

/**
 * Unit 1's 6 benchmark codes, in mission order. Explicit list rather than
 * `code: { startsWith: 'SS.7.CG.1.' }` + sequenceOrder — sequenceOrder is
 * scoped per-unit (see unlockNextBenchmark), and Phase 15 added Unit 2 as
 * SS.7.CG.1.7–.11, so the prefix alone matches both units and a plain
 * sequenceOrder sort would interleave them unpredictably.
 */
export const UNIT1_BENCHMARK_CODES = [
  'SS.7.CG.1.1',
  'SS.7.CG.1.2',
  'SS.7.CG.1.3',
  'SS.7.CG.1.4',
  'SS.7.CG.1.5',
  'SS.7.CG.1.6',
] as const

export async function loadBenchmarksByCode(
  codes: readonly string[]
): Promise<Array<{ id: string; code: string }>> {
  const rows = await prisma.benchmark.findMany({
    where: { code: { in: [...codes] } },
    select: { id: true, code: true },
  })
  const byCode = new Map(rows.map((r) => [r.code, r]))
  const missing = codes.filter((c) => !byCode.has(c))
  if (missing.length > 0) {
    throw new Error(`Missing seeded benchmark(s): ${missing.join(', ')}. Run \`npm run db:seed\` first.`)
  }
  return codes.map((c) => byCode.get(c)!)
}

export async function getBenchmarkProgressStatus(
  studentId: string,
  benchmarkId: string
): Promise<StudentProgressStatus | null> {
  const row = await prisma.studentProgress.findUnique({
    where: { studentId_benchmarkId: { studentId, benchmarkId } },
    select: { status: true },
  })
  return row?.status ?? null
}
